services:
  - type: web
    name: json-server
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    build:
      command: npm install && npm install json-server
